name: docker
on:
  push:
    branches:
      - v2.0
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2 
      -
        name: bulid and test
        run: |
          docker build -t fmartinve/spring-petclinic:2.0 --no-cache .
          docker run -d -p 80:8080 fmartinve/spring-petclinic:2.0
          while true
            do
              sleep 1
              docker ps | grep Up && break
            done
          while true
            do
              sleep 1
              docker ps | grep java && break
            done
          while true
            do
              sleep 1
              curl localhost -I | grep 200 && break
            done
         
    
